({
    name:"&and;",
    depends:["&not;"],  
    goals:[
        // Future definitions using the biconditional can be automatic, but
        // this definition *of* the biconditional must be manual.
        {Core:[[],[0,[1,
                      [1,
                       [2,0,1],[0,[1,0,[0,1]]]],
                      [0,[1,   [0,[1,0,[0,1]]],
                       [2,0,1]]]]],[]],
         Skin:{TermNames:["&not;","&rarr;","&and;"]},
         Tree:{Cmd:"defthm",Definiendum: 2}
        },
        {Core:[[],[0,[1,0,1],[2,[0,0,[2,1]]]],[]],
         Skin:{TermNames:["&rarr;","&and;","&not;"]}},
        {Core:[[],[0,[1,[0,0,[1,1]]],[2,0,1]],[]],
         Skin:{TermNames:["&rarr;","&not;","&and;"]}},
        {Core:[[],[0,[0,0,1],[0,[1,0,2],[1,1,2]]],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,[0,0,1],[0,[1,2,0],[1,2,1]]],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,[1,0,1],0],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,[1,0,1],1],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,0,[0,1,[1,0,1]]],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,0,[1,0,0]],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,[1,0,1],[1,1,0]],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,[0,0,1],[0,0,[1,0,1]]],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,[0,0,[0,1,2]],[0,[1,0,1],2]],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,[1,0,[0,0,1]],1],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,[1,0,[0,1,2]],[0,1,[1,0,2]]],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
        {Core:[[],[0,[1,[0,0,1],[0,2,3]],[0,[1,0,2],[1,1,3]]],[]],
         Skin:{TermNames:["&rarr;","&and;"]}},
],
})
