{
    name:"&harr;",
    depends:["&and;"],  // TODO: figure out a content-addressable scheme
    goals:[
        {Core:[[],[0,[1,0,0],[1,1,1]],[]],
         Skin:{TermNames:["&and;","&rarr;"]}},

        {Core:[[],[0,[1,[2,1,2],[0,[1,1,2],[1,2,1]]],
                   [1,[0,[1,1,2],[1,2,1]],[2,1,2]]],[]],
         Skin:{TermNames:["&and;","&rarr;","&harr;"]},
         Tree:{Cmd:"defthm",Definiendum: 2}},

        {Core:[[],[0,[1,0,1],[2,[0,0,1],[0,1,0]]],[]],
         Skin:{TermNames:["&rarr;","&harr;","&and;"]},
        },
        {Core:[[],[0,[1,[0,0,1],[0,1,0]],[2,0,1]],[]],
         Skin:{TermNames:["&rarr;","&and;","&harr;"]}},
        {Core:[[],[0,[1,0,1],[0,0,1]],[]],
         Skin:{TermNames:["&rarr;","&harr;"]}},
        {Core:[[],[0,[1,0,1],[0,1,0]],[]],
         Skin:{TermNames:["&rarr;","&harr;"]}},
        {Core:[[],[0,[1,0,1],[1,[0,1,2],[0,0,2]]],[]],
         Skin:{TermNames:["&rarr;","&harr;"]}},
        {Core:[[],[0,[1,0,1],[1,[0,2,0],[0,2,1]]],[]],
         Skin:{TermNames:["&rarr;","&harr;"]}},
        {Core:[[],[0,[1,0,1],[1,[1,0,2],[1,1,2]]],[]],
         Skin:{TermNames:["&rarr;","&harr;"]}},
        {Core:[[],[0,[1,0,1],[1,[1,2,0],[1,2,1]]],[]],
         Skin:{TermNames:["&rarr;","&harr;"]}},
        {Core:[[],[0,0,[0,[1,0,1],1]],[]],
         Skin:{TermNames:["&rarr;","&harr;"]}},
        {Core:[[],[0,0,[0,[1,1,0],1]],[]],
         Skin:{TermNames:["&rarr;","&harr;"]}},
        {Core:[[],[0,[1,0,1],[1,[2,,0,2],[2,1,2]]],[]],
         Skin:{TermNames:["&rarr;","&harr;","&and;"]}},
        {Core:[[],[0,[1,0,1],[1,[2,2,0],[2,2,1]]],[]],
         Skin:{TermNames:["&rarr;","&harr;","&and;"]}},
        {Core:[[],[0,[1,0,1],[1,[2,1],[2,0]]],[]],
         Skin:{TermNames:["&rarr;","&harr;","&not;"]}},
    ],
}
